apiVersion: apps/v1
kind: Deployment
metadata:
  name: regui
  labels:
    apps: regui
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: regui
  template:
    metadata:
      labels:
        apps: regui
    spec:
      containers:
      - name: regui
        image: bessenyeicsilla/genuinetools_reg:latest
        env:
        - name: REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              name: docker-push-secret
              key: username
        - name: REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: docker-push-secret
              key: password
        command: ["sh", "-c", "reg server --asset-path /ui/ -r https://docker-registry.csikoste.com -u $(REGISTRY_USERNAME) -p $(REGISTRY_PASSWORD)"]
        ports:
        - containerPort: 8080
