apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: regui
  annotations:
    # NOTE: default- prefix is the middleware's namespace
    traefik.ingress.kubernetes.io/router.middlewares: default-https-redirect@kubernetescrd

spec:
  rules:
  - host: reg.csikoste.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: regui
            port:
              name: http
