apiVersion: v1
kind: ConfigMap

metadata:
  name: hook

data:
  post-hook.sh: |
    #/bin/sh
    ln -s live/csikoste.com/fullchain.pem /etc/letsencrypt/tls.crt
    ln -s live/csikoste.com/privkey.pem /etc/letsencrypt/tls.key

---
apiVersion: v1
kind: ConfigMap

metadata:
  name: kustomization

data:
  kustomization.yaml: |
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    secretGenerator:
      - name: csikoste-wildcard-tls
        files:
          - letsencrypt/tls.crt
          - letsencrypt/tls.key
        type: kubernetes.io/tls
    generatorOptions:
      annotations:
        subject: /CN=*.csikoste.com
      disableNameSuffixHash: true
