apiVersion: v1
kind: ServiceAccount

metadata:
  name: kubectl

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: csikoste-wildcard-tls-patch

rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - csikoste-wildcard-tls
    verbs:
      - get
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: kubectl-csikoste-wildcard-tls-patch

subjects:
  - kind: ServiceAccount
    name: kubectl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: csikoste-wildcard-tls-patch
