apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hellos.crd.y2k
spec:
  group: crd.y2k
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: hellos
    singular: hello
    kind: Hello
    categories:
      - all
  #preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            name:
              type: string
