apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crd.yaml
  - deployment.yaml
  - hello.yaml
  - rbac.yaml

configMapGenerator:
  - name: hello-controller-script
    files:
      - controller.sh

generatorOptions:
  disableNameSuffixHash: true
