apiVersion: v1
kind: ServiceAccount

metadata:
  name: hello-operator

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole

metadata:
  name: hello-operator

rules:
  - apiGroups:
      - crd.y2k
    resources:
      - hellos
    verbs:
      - list

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding

metadata:
  name: hello-operator

subjects:
  - kind: ServiceAccount
    name: hello-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: hello-operator
  apiGroup: rbac.authorization.k8s.io
