apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository

metadata:
  name: twuni

spec:
  interval: 1h0m0s
  url: https://helm.twun.io

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: docker-registry

spec:
  chart:
    spec:
      chart: docker-registry
      sourceRef:
        kind: HelmRepository
        name: twuni
      version: 2.2.2
  interval: 1h0m0s
  values:
    # NOTE: `extraEnvVars`, `extraVolumeMounts`, `extraVolumes` are supporting `.Values.secrets.htpasswd`-management from a SealedSecret
    extraEnvVars:
      - name: REGISTRY_AUTH
        value: htpasswd
      - name: REGISTRY_AUTH_HTPASSWD_REALM
        value: Registry Realm
      - name: REGISTRY_AUTH_HTPASSWD_PATH
        value: /auth/htpasswd
    extraVolumeMounts:
      - name: auth
        mountPath: /auth
        readOnly: true
    extraVolumes:
      - name: auth
        secret:
          secretName: docker-push-secret
          items:
            - key: htpasswd
              path: htpasswd
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: default-https-redirect@kubernetescrd # FIXME
      className: ''
      hosts:
        - docker-registry.csikoste.com
      tls:
        - secretName: csikoste-wildcard-tls
    persistence:
      enabled: true
      size: 50Gi
      storageClass: manual
