apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-registry-pv-secret
spec:
  encryptedData:
    node.session.auth.username: AgCbCQ/Za4rlS/I3sFIFxfRAVYuJrrDEYsgr6ME5OatbVEkINkPkAjCpnmzG3p7jI+yedj4oTrfoDaJ9YOeOMD+uPKEsDb5Hs+OeEVTmJMZ+wVwNfz66JULyQnSkPUZ1SfQV+Q1Rf7MWBeNgQQsggZSH3A5I1S0TCRlVPUq5xZky4hQx20VuPLkQrhf6hK920DyHuaLVVoeTPf3ShU/K0Nn3ngbMPBp0D1d2ghIwj+n/PWlpIzDBUZqTgxhnxJlBbX5h1o/DHuaplZfcZ/NsoWvPOv7zuhLKq9MtfBuMnmBlzmZ0y3O1DtfswqrJ7+QkB5Z7Ntg1Em9Msa9z6mV8JMC0D5g1oEkM5LfwvfI2EqvJIia5ITRWsI8U5wJWK9PZWAUBB/UQvIRsQFAeR+gn2uWfAIdr6+E3GqHid+bR1u5aDq1w/kGGwvKCtHyBF1bE6UsLfkpyJG+wRAMqxE/vy1KlZTyALgwZDJ1ry7SK6scnCaneDJUVRnXlwdmR0Kb7fKzGp30HvZ8gYAeVW9mg18G2/rtSMfgW2YvWzp3Q9oQO/gAoQUVtxC3KPgA4IhnWeXDXKF6KmRxx1B2O40bF1RNqcgw46rtA7rKT0DvMKAFUUUmDb93w+m/UQ6WaJ3EJvIsqyThOkMSzhRF/94B4pGZH2zUNwqRemtZ+Lhyev8TlaVW3k5LY0/Ye1ZteXtdKmcAejlGSJLm/lR2jDyMe75E=
    node.session.auth.password: AgC9Mr/lXLxSz4cHdJ0EsVOWHH89nh99LjSoNulrxOWWPHEBrl1F3cKIjJqu8MauNMPygOjF2NFL288heUqsxBARJZynELxnbBebTl0852PMP1aQrAX7FJ+SoTTGEaOkLID9mnOKYU5Q+rxeXcc4YmxLc1SNqKprF5PwW462kAnB7KlQ8J8x4/dfNRqnUz4z3tvxfBCBZFPMftZr1AZpFwP2S2UAwvVjUxA2xLxFpYbnKJeYVLCINGsNeFpw5ydbStptQQ2w50/fviYsdVIzfjIpMxkGfUZBUYKryE0dTbhZI7SkwLUuVWrFdegO+dC4ULQn6YuEXWfh2ds7/JyCxJzuh48WyAQBYkVv92bLoyr7reXQuA1Gc9/qPcbJ+QXWRM5yiVNwGVuWiTC18vwqDywpuYoxmfFRTKhkxP5hfYjXd9Ndu5VdjZdiNlXN2KmVeDwC24bqEWCuDGhiZ/rm2MWm6ceTuywIpD/bNNadOBTFzP35joOwPHSxmAKt/ad6WnpxWZYvQRBz6TrX3MqIPX43x3juhe7TQVLs+mQAKuRcsawsJQk4yn04k4LIx7IedHUcdUB7UPdECYRBUz5Al3v+0SnmerjmRFdJhj5DwLd6wuLonmNHDifFElUQ825u/oVRYK0ZR0dl+kbw2uxOgbf7G6HAEevp947IoxgXCjq91JP7Ipw8uJwH/rVhT/4xIkwAEGVdP4ss0hQ9G4XGYgYg
  template:
    type: kubernetes.io/iscsi-chap
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv
  annotations:
    pv.kubernetes.io/provisioned-by: manually
spec:
  storageClassName: manual
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: docker-registry
    namespace: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 10.100.0.101 # nas.csikoste.com
    iqn: iqn.2013-03.com.wdc:mycloudex2ultra:docker-registry
    lun: 0
    fsType: ext4
    chapAuthSession: true
    secretRef:
      name: docker-registry-pv-secret
