apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - ingress.yaml
  - persistent_volume.yaml
  - service.yaml

labels:
  - pairs:
      app: home-assistant
    includeSelectors: true

images:
  - name: ghcr.io/home-assistant/home-assistant
    #newName: docker-registry.csikoste.com/home-assistant/home-assistant # FIXME
    newTag: 2025.9.1
