# uri: http://cluster/jenkins
# username: admin
# password: printf $(kubectl get secret --namespace default jenkins -o jsonpath="{.data.jenkins-admin-password}" | base64 --decode);echo
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: jenkins
spec:
  chart: stable/jenkins
  version: 1.27.0
  valuesContent: |
    master:
      image: matefarkas/jenkins
      tag: 2.222.4-slim-arm
      imagePullPolicy: "Always"
      jenkinsUriPrefix: ''
      serviceType: ClusterIP
      ingress:
        enabled: true
        hostName: jenkins.csikoste.com
        tls:
          - secretName: csikoste-wildcard-tls
        annotations:
          traefik.ingress.kubernetes.io/redirect-entry-point: https
      installPlugins:
        - kubernetes:1.26.0
        - workflow-job:2.39
        - workflow-aggregator:2.6
        - credentials-binding:1.23
        - git:4.2.2
        - configuration-as-code:1.41
      sidecars:
        configAutoReload:
          enabled: false
    agent:
      image: matefarkas/jenkins-jnlp-agent
      tag: 3.29-slim-arm
      podName: jenkins-agent
    persistence:
      enabled: false
