apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - secret.yaml

configMapGenerator:
  - name: tinyproxy-config
    files:
      - files/tinyproxy.conf

generatorOptions:
  disableNameSuffixHash: true
