apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

resources:
  - daemon_set.yaml
  - rbac.yaml
  - service_account.yaml

images:
  - name: fluent/fluent-bit
    newTag: 3.1.4-arm64

configMapGenerator:
  - name: fluent-bit-config
    files:
      - files/fluent-bit.conf
      - files/parsers.conf

generatorOptions:
  disableNameSuffixHash: true
