apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app: mqtt
    includeSelectors: true

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: mqtt
    files:
      - acl_file
      - mosquitto.conf

secretGenerator:
  - name: mqtt
    files:
      - password_file
